### ISSUE TITLE
StructureAnalyzer fails at 6OYV

### ISSUE THREAD

**Issue by conradhuebler** [Cardypro/StructureAnalyzer#3] opened 2021-01-11 09:34 UTC
The StructureAnalzer fails to create a mrv file for _6OYV_.

For this, I added 
    "Fe": 2
to the array of  **vdwRadii**.
`
StructureAnalyzer("6OYV", "EST")

 ExecutiveLoad-Detail: Detected mmCIF
Analyzing EST601...
Traceback (most recent call last):
  File "StructureAnalyzer.py", line 405, in StructureAnalyzer
    writeXML(currGraph, interactionList, pdbCode, ligands)
  File "StructureAnalyzer.py", line 234, in writeXML
    str(dictionary[interactions.atomB.identifierString]) + "\"/>\n")
KeyError: '6OYV//A/VAL`126/HG11'
`

**Comment by Cardypro** [comment] 2021-01-12 00:12
Thanks for creating this issue - I always appreciate help from the community. The problem was caused by not removing all hydrogen atoms from the selection. It is  fixed in the recent commit.

**Closed as completed by Cardypro** 2021-01-12 00:12 UTC
